pipeline {
  agent {
    kubernetes {
      label 'build-test-pod'
      defaultContainer 'xtext-buildenv'
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: jnlp
            image: 'eclipsecbi/jenkins-jnlp-agent'
            args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
            volumeMounts:
            - mountPath: /home/jenkins/.ssh
              name: volume-known-hosts
          - name: eclipsecbi-fedora
            image: eclipsecbi/fedora-gtk3-mutter:29-gtk3.24
            tty: true
          - name: xtext-buildenv
            image: docker.io/smoht/xtext-buildenv:0.2
            tty: true
          volumes:
          - configMap:
              name: known-hosts
            name: volume-known-hosts
    '''
    }
  }
  
  parameters {
    string(name: 'AUTHOR_NAME', description: 'Committer name (used for Git commits)')
    string(name: 'AUTHOR_EMAIL', description: 'Committer email address (used for Git commits)')
    string(name: 'SOURCE_BRANCH', defaultValue: 'master', description: 'Source Git Branch')
    string(name: 'TARGET_BRANCH', defaultValue: 'releng_set_version', description: 'Target Git Branch')
    booleanParam(name: 'ALL_REPOSITORIES', defaultValue: true, description: 'Perform modification on ALL repositories. If NOT checked, the TARGET_REPOSITORY below is used.')
    choice(name: 'TARGET_REPOSITORY', choices: ['xtext-lib', 'xtext-core', 'xtext-extras', 'xtext-eclipse', 'xtext-xtend', 'xtext-maven', 'xtext-web', 'xtext-idea', 'xtext-umbrella'], description: 'ONLY used when ALL_REPOSITORIES is NOT SET. Repository to modify.')
    string(name: 'NEW_XTEXT_VERSION', description: 'New Xtext version to set (major.minor.micro, without SNAPSHOT)')
    booleanParam(name: 'DRY_RUN', defaultValue: false, description: 'Dry run mode')
  }

  options {
    buildDiscarder(logRotator(numToKeepStr:'2'))
    disableConcurrentBuilds()
  }

  stages {
    stage('Checkout') {
      steps {
          checkout scm
          script {
            def gitFunctions    = load 'build-tools/git_functions.groovy'
            
            // Check preconditions
            if (!AUTHOR_NAME?.trim() || !AUTHOR_EMAIL?.trim()) {
              currentBuild.result = 'ABORTED'
              error('Author required.')
            }
            if (TARGET_BRANCH == 'master') {
              currentBuild.result = 'ABORTED'
              error('TARGET_BRANCH \'master\' is disallowed...')
            }
            if (!NEW_XTEXT_VERSION?.matches('\\d\\.\\d+\\.\\d+')) {
              currentBuild.result = 'ABORTED'
              error("NEW_XTEXT_VERSION '${NEW_XTEXT_VERSION}' Invalid...")
            }

            // list of Xtext repository names
            def repositoryNames = ALL_REPOSITORIES ? ['xtext-lib', 'xtext-core', 'xtext-extras', 'xtext-eclipse', 'xtext-xtend', 'xtext-maven', 'xtext-web', 'xtext-umbrella'] : [TARGET_REPOSITORY]
            
            // checkout source branch for each repository and create the target branch
            repositoryNames.each {
              dir(it) {
                git url: "git@github.com:eclipse/${it}.git", branch: SOURCE_BRANCH, credentialsId: CREDENTIAL_ID_GENIE_XTEXT_GITHUB
              }
              // When release branch already exists, then delete it and create a new one
              if (gitFunctions.branchExists(it, TARGET_BRANCH)){
                gitFunctions.deleteBranch(TARGET_BRANCH)
              }
              gitFunctions.createBranch(it, TARGET_BRANCH)
            }
          }
      }
    }

    stage('Set Xtext Version') {
      when {
        expression { params.NEW_XTEXT_VERSION?.trim() }
      }
      steps {
        script {
          def git    = load 'build-tools/git_functions.groovy'
          def gradle = load 'build-tools/gradle_functions.groovy'
          def FROM_VERSION = gradle.getXtextVersion()
          // list of Xtext repository names
          def repositoryNames = ALL_REPOSITORIES ? ['xtext-lib', 'xtext-core', 'xtext-extras', 'xtext-eclipse', 'xtext-xtend', 'xtext-maven', 'xtext-web', 'xtext-umbrella'] : [TARGET_REPOSITORY]
          def git    = load 'build-tools/git_functions.groovy'
          
          // MODIFY
          sh "sh build-tools/fixVersions.sh -f $FROM_VERSION -t $NEW_XTEXT_VERSION -b StoS"

          // COMMIT
          repositoryNames.each {
            git.getGitChanges(it)
            git.commit(it, "[releng] Set version to ${NEW_XTEXT_VERSION}", AUTHOR_NAME, AUTHOR_EMAIL)
          }
        } // script
      }
    }
    
    stage('Push') {
      when {
        expression { !params.DRY_RUN }
      }
      steps {
        
        // TODO: git push does not work in the xtext-buildenv container
        //   No user exists for uid 1000100000
        //   fatal: Could not read from remote repository.
        // But jnlp does not contain hub utility
        container ('eclipsecbi-fedora') {  
          script {
          def git    = load 'build-tools/git_functions.groovy'
          def repositoryNames = ALL_REPOSITORIES ? ['xtext-lib', 'xtext-core', 'xtext-extras', 'xtext-eclipse', 'xtext-xtend', 'xtext-maven', 'xtext-web', 'xtext-umbrella'] : [TARGET_REPOSITORY]
          if(!params.DRY_RUN){
            sshagent([CREDENTIAL_ID_GENIE_XTEXT_GITHUB]) {
              sh "echo pushing branch ${TARGET_BRANCH}"
              repositoryNames.each {
                git.pushGitChanges(it, TARGET_BRANCH, true)
              }
            }
          }
          }
        
        }
          script {
          def git    = load 'build-tools/git_functions.groovy'
          def repositoryNames = ALL_REPOSITORIES ? ['xtext-lib', 'xtext-core', 'xtext-extras', 'xtext-eclipse', 'xtext-xtend', 'xtext-maven', 'xtext-web', 'xtext-idea', 'xtext-umbrella'] : [TARGET_REPOSITORY]
          if(!params.DRY_RUN){
            sshagent([CREDENTIAL_ID_GENIE_XTEXT_GITHUB]) {
              repositoryNames.each {
                git.createPullRequest('eclipse',it,'[releng] Set xtext version',TARGET_BRANCH,SOURCE_BRANCH)
              }
            }
          }
          }
      } // steps
    } // stage
  } // stages
}
